Repository Ayon-SSP/The-SDE-Prep, pull requests merged in 2022-10, with the labels that each got.

#12 Added subset_sum [Striver Sheet]
  4]_SDE Sheet's/Strivers SDE Sheet/Day 09 [Recursion]/Subset_Sums.cpp
Labels: good first issue, hacktoberfest

#16 [ Full ReadMe cleanup ]
  CONTRIBUTING.md
  README.md
  etc/CREDITS.md
Labels: hacktoberfest, hactoberfest-accepted

#13 Added rotate matrix program in Java.
  4]_SDE Sheet's/Strivers SDE Sheet/Day 02 [Arrays Part-II]/Rotate_Matrix.java
Labels: hacktoberfest, hactoberfest-accepted

#20 Maximum and Minimum element in the Array📚.
  4]_SDE Sheet's/Love Babbar DSA Sheet/C++/01]_Arrays/Find the Maximum and Minimum element in the Array.cpp
Labels: hacktoberfest-accepted

#22 SDE Sheet Folders🗃️ Arrange♻️
  4]_SDE Sheet's/Strivers SDE Sheet/Day 10 [Recursion and Backtracking]/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#25 Added merge and quick sort in C
  2]_Algorithms/2]_Sorting/mergeSort.c
  2]_Algorithms/2]_Sorting/quickSort.c
Labels: hacktoberfest, hacktoberfest-accepted

#15 Create knapsack_problem.cpp
  2]_Algorithms/9]_Dynamic Programming/knapsack_problem.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#28 Added binary tree
  1]_Data Structures/5]_Tree/2]_Binary Tree/Binary_Tree.cpp
Labels: hacktoberfest-accepted

#27 SDE Sheet Folders📂 Arrange🗃️
  4]_SDE Sheet's/Strivers SDE Sheet/Day 21 [Binary Search Tree Part-II]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 22 [Binary Trees[Miscellaneous]]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 23 [Graph]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 24 [Graph Part-II]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 25 [Dynamic Programming]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 26 [Dynamic Programming Part-II]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 27 [Trie]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 28 [Operating System]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 29 [DBMS]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 30 [Computer Networks]/README.md
  4]_SDE Sheet's/Strivers SDE Sheet/Day 31 [Project Overview]/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#29 Create QueueReversal.cpp
  1]_Data Structures/4]_Queue/1]_Simple Queue/QueueReversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#30 Create N_Queen_Problem.cpp
  4]_SDE Sheet's/Strivers SDE Sheet/Day 09 [Recursion]/N_Queen_Problem.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#35 Added Heap, Selection, and Insertion sort in C
  2]_Algorithms/2]_Sorting/heapSort.c
  2]_Algorithms/2]_Sorting/insertionSort.c
  2]_Algorithms/2]_Sorting/selectionSort.c
Labels: hacktoberfest, hacktoberfest-accepted

#34 Added solution for reversing a linked list
  4]_SDE Sheet's/Strivers SDE Sheet/Day 05 [Linked List]/Reverse_a_linked_list.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#32 Solved Pascal's Triangle
  4]_SDE Sheet's/Strivers SDE Sheet/Day 01 [Arrays]/PascalTriangle.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#33 Code for Rotate Matrix by 90 degrees added
  4]_SDE Sheet's/Love Babbar DSA Sheet/C++/02]_Arrays Part-II/Rotate Matrix by 90 degrees.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#36 Added BIT implementatiom
  1]_Data Structures/5]_Tree/4]_Binary Indexed Tree/Binary_Indexed_Tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#47 Implemented linear and binary search in Python
  2]_Algorithms/1]_Searching/_01]_Linear Search.py
  2]_Algorithms/1]_Searching/_02]_Binary Search.py
Labels: hacktoberfest, hacktoberfest-accepted

#45 Added Binary Tree implementation in Python
  1]_Data Structures/5]_Tree/2]_Binary Tree/binaryTree.py
Labels: hacktoberfest, hacktoberfest-accepted

#37 Solved Kadane's Algorithm
  4]_SDE Sheet's/Strivers SDE Sheet/Day 01 [Arrays]/KadaneAlgorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#44 Added solution for middle of linked list
  4]_SDE Sheet's/Strivers SDE Sheet/Day 05 [Linked List]/Middle_of_linked_list.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#46 Added stack implementation in Python
  1]_Data Structures/3]_Stack/stack.py
Labels: hacktoberfest, hacktoberfest-accepted

#50 Created Travelling_salesman.cpp
  2]_Algorithms/9]_Dynamic Programming/Travelling_salesman.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#52 Added Python Sorting Codes
  2]_Algorithms/2]_Sorting/_10]_Shell Sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#58 Added Bellman-ford algorithm
  2]_Algorithms/9]_Dynamic Programming/bellman-ford.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#62 Added 2-Sum-Problem solution
  4]_SDE Sheet's/Strivers SDE Sheet/Day 04 [Arrays Part-IV]/2-Sum-Problem.py
Labels: hacktoberfest, hacktoberfest-accepted

#61 Added Dijkstra algo
  2]_Algorithms/7]_Greedy/Dijkstra.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#64 Added Linked List solutions
  4]_SDE Sheet's/Strivers SDE Sheet/Day 05 [Linked List]/Add_Two_Numbers.cpp
  4]_SDE Sheet's/Strivers SDE Sheet/Day 05 [Linked List]/Delete_Node_in_a_Linked_List.cpp
  4]_SDE Sheet's/Strivers SDE Sheet/Day 05 [Linked List]/Merge_Two_Sorted_Lists.cpp
  4]_SDE Sheet's/Strivers SDE Sheet/Day 05 [Linked List]/Remove_Nth_Node_From_End_of_List.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#63 Created Matrix_Chain_Multiplication.cpp
  2]_Algorithms/9]_Dynamic Programming/Matrix_Chain_Multiplication.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#65 Added Linked List II solutions
  4]_SDE Sheet's/Strivers SDE Sheet/Day 02 [Arrays Part-II]/Count_Inversions.cpp
  4]_SDE Sheet's/Strivers SDE Sheet/Day 02 [Arrays Part-II]/Find_the_Duplicate_Number.cpp
  4]_SDE Sheet's/Strivers SDE Sheet/Day 02 [Arrays Part-II]/Merge_Intervals.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#69 Added folder for standard DP problems
  3]_CP/DP/Coin Change - Maximum ways.cpp
  3]_CP/DP/Count of subsets with a given sum(top-down).cpp
  3]_CP/DP/Count of subsets with given difference.cpp
  3]_CP/DP/Equal Sum Partition (top-down).cpp
  3]_CP/DP/Knapsack/zero_one Knapsack (memoized).cpp
  3]_CP/DP/Knapsack/zero_one Knapsack (recursive).cpp
  3]_CP/DP/Knapsack/zero_one Knapsack (top-down).cpp
  3]_CP/DP/Longest Common Subsequence/LCS Length (Memoization).cpp
  3]_CP/DP/Longest Common Subsequence/LCS Length (Top - Down).cpp
  3]_CP/DP/Longest Common Subsequence/LCS Length (recursive).cpp
  3]_CP/DP/Longest Common Subsequence/Longest Common Substring Length.cpp
  3]_CP/DP/Longest Common Subsequence/Printing LCS.cpp
  3]_CP/DP/Minimum Subset Sum Difference.cpp
  3]_CP/DP/Subset Sum Problem/Subset Sum Problem (recursive).cpp
  3]_CP/DP/Subset Sum Problem/Subset Sum Problem (top-down).cpp
Labels: hacktoberfest, hacktoberfest-accepted

#66 Added solution for 4 sum
  4]_SDE Sheet's/Strivers SDE Sheet/Day 04 [Arrays Part-IV]/4sum.java
Labels: hacktoberfest, hacktoberfest-accepted

#70 Added folder for number theory
  3]_CP/Number Theory/GCD by euclid's algo.cpp
  3]_CP/Number Theory/Matrix Exponentiation.cpp
  3]_CP/Number Theory/Modular Exponentiation.cpp
  3]_CP/Number Theory/Prime Factorisation Using Sieve.cpp
  3]_CP/Number Theory/nth fibonacci number.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#73 created(advanced-data-structures): added Trie and Segment Tree
  1]_Data Structures/7]_Trie/Concatinated_Words.cpp
  1]_Data Structures/7]_Trie/Implement_Trie.cpp
  1]_Data Structures/7]_Trie/Palindrome_Pairs.cpp
  1]_Data Structures/7]_Trie/README.md
  1]_Data Structures/8]_Segment Tree/Max_Query_In_Range.cpp
  1]_Data Structures/8]_Segment Tree/README.md
  1]_Data Structures/8]_Segment Tree/Range_Sum_Query.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#79 Added Graphs folder in Algorithms
  2]_Algorithms/10]_Graphs/KosaRaju's_Algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#83 Create bestTimeToBuyAndSell.cpp
  bestTimeToBuyAndSell.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#94 Delete desktop.ini
  desktop.ini
Labels: hacktoberfest, hacktoberfest-accepted

#95 cleanup _ more
  2]_Algorithms/2]_Sorting/_04]_Merge Sort.py
  2]_Algorithms/5]_Recursion/code.chunk.py.txt
  3]_CP/DP/Coin Change - Maximum ways.cpp
  3]_CP/DP/Count of subsets with given difference.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#98 Added Linked List programs
  1]_Data Structures/2]_Linked List/10_insertinginsorted.c
  1]_Data Structures/2]_Linked List/11_deletingnode.c
  1]_Data Structures/2]_Linked List/12_checksorting.c
  1]_Data Structures/2]_Linked List/13_removeduplicates.c
  1]_Data Structures/2]_Linked List/14_reversinglist.c
  1]_Data Structures/2]_Linked List/15_concatenation.c
  1]_Data Structures/2]_Linked List/16_merginglists.c
  1]_Data Structures/2]_Linked List/17_loopcheck.c
  1]_Data Structures/2]_Linked List/18_circularlinkedlist.c
  1]_Data Structures/2]_Linked List/19_insertingincircularlinkedlist.c
  1]_Data Structures/2]_Linked List/1_makinglinkedlist.c
  1]_Data Structures/2]_Linked List/20_deletingincircularLL.c
  1]_Data Structures/2]_Linked List/21_doublelinkedlist.c
  1]_Data Structures/2]_Linked List/22_insertingindoubleLL.c
  1]_Data Structures/2]_Linked List/23_reversedoubleLL.c
  1]_Data Structures/2]_Linked List/24_polynomial.c
  1]_Data Structures/2]_Linked List/25_polynomialaddition.c
  1]_Data Structures/2]_Linked List/26_polynomialmultiplication.c
  1]_Data Structures/2]_Linked List/27_sortingLL.c
  1]_Data Structures/2]_Linked List/2_displayinglinkedlist.c
  1]_Data Structures/2]_Linked List/3_countingnodes.c
  1]_Data Structures/2]_Linked List/4_sumofallelements.c
  1]_Data Structures/2]_Linked List/5_maximumelement.c
  1]_Data Structures/2]_Linked List/6_searchinginlinkedlist.c
  1]_Data Structures/2]_Linked List/7_improvingsearching.c
  1]_Data Structures/2]_Linked List/8_insertingnode.c
  1]_Data Structures/2]_Linked List/9_insertlast.c
  2]_Algorithms/7]_Greedy/kadane.cpp
  2]_Algorithms/7]_Greedy/maximumwraparraysum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#86 Added merge Sort in cpp
  2]_Algorithms/2]_Sorting/Source/_MergeSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#89 Sorting in C++
  1]_Data Structures/3]_Stack/Paranthesischeck.c
  1]_Data Structures/3]_Stack/Postfixvevaluation.c
  1]_Data Structures/3]_Stack/Stackoperation.c
  1]_Data Structures/3]_Stack/Stackusinglinkedlist.c
  1]_Data Structures/3]_Stack/StringPalindromeusingstack.c
  1]_Data Structures/3]_Stack/Towerofhanoi.c
  1]_Data Structures/3]_Stack/infixtopostfix.c
  2]_Algorithms/2]_Sorting/Sorting in C++/Bubblesort.cpp
  2]_Algorithms/2]_Sorting/Sorting in C++/Countingsort.cpp
  2]_Algorithms/2]_Sorting/Sorting in C++/Heapsort.cpp
  2]_Algorithms/2]_Sorting/Sorting in C++/Insertionsort.cpp
  2]_Algorithms/2]_Sorting/Sorting in C++/Mergesort.cpp
  2]_Algorithms/2]_Sorting/Sorting in C++/Quicksort.cpp
  2]_Algorithms/2]_Sorting/Sorting in C++/Radixsort.cpp
  2]_Algorithms/2]_Sorting/Sorting in C++/Selectionsort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#90 Added Prims and Kruskal
  2]_Algorithms/10]_Graphs/Kruskals_Algorithm.cpp
  2]_Algorithms/10]_Graphs/Prims_Algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#87 Added Floyd warshall algorithm code under Algorithms in Graphs folder
  2]_Algorithms/10]_Graphs/Floyd_warshall_algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#96 Added solution for max path sum
  4]_SDE Sheet's/Strivers SDE Sheet/Day 19 [Binary Tree part-III]/Maximum_Path_Sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#97 Added solution for symmetric binary tree
  4]_SDE Sheet's/Strivers SDE Sheet/Day 19 [Binary Tree part-III]/Symmetric_Binary_Tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#137 Word Wrap
  4]_SDE Sheet's/Love Babbar DSA Sheet/C++/String/Word Wrap .cpp
Labels: hacktoberfest, hacktoberfest-accepted

#143 Create majority element
  4]_SDE Sheet's/Strivers SDE Sheet/Day 03 [Arrays Part-III]/majority element
Labels: hacktoberfest, hacktoberfest-accepted

#167 Create nextGreaterElement.cpp
  1]_Data Structures/3]_Stack/nextGreaterElement.cpp
Labels: hacktoberfest, hacktoberfest-accepted
