Repository Ayon-SSP/The-SDE-Prep, pull requests merged in 2023-10, with the labels that each got.

#169 Create Minimum_Window_Substring.cpp
  2]_Algorithms/4]_Strings/Minimum_Window_Substring.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#172 Create First_and_Last_Position.py
  2]_Algorithms/3]_BinarySearch/First_and_Last_Position.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#171 Create Substring_with_Concatenation_of_All_Words.py
  2]_Algorithms/4]_Strings/Substring_with_Concatenation_of_All_Words.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#175 Create Design_HashMap.py
  1]_Data Structures/1]_Array/Design_HashMap.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#177 Create Merge_Strings_Alternately.py
  2]_Algorithms/4]_Strings/Merge_Strings_Alternately.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#178 Create Find_the_Highest_Altitude.py
  1]_Data Structures/1]_Array/Find_the_Highest_Altitude.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#179 Create Find_Pivot_Index.py
  1]_Data Structures/1]_Array/Find_Pivot_Index.py
  1]_Data Structures/1]_Array/Maximum_Average_Subarray_I.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#180 Create Daily_Temperatures.py
  1]_Data Structures/1]_Array/Daily_Temperatures.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#182 Create Edit_Distance.cpp
  3]_CP/DP/Edit_Distance.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023

#185 Create Zigzag_Conversion.c++
  2]_Algorithms/4]_Strings/Zigzag_Conversion.c++
Labels: hacktoberfest-accepted, hacktoberfest2023

#186 Create String_to_Integer_(atoi).cpp
  2]_Algorithms/4]_Strings/String_to_Integer_(atoi).cpp
Labels: hacktoberfest-accepted, hacktoberfest2023

#187 Create Longest_Palindromic_Substr.cpping
  2]_Algorithms/4]_Strings/Longest_Palindromic_Substr.cpping
Labels: hacktoberfest-accepted, hacktoberfest2023

#188 Create Palindrome_Number.cpp
  2]_Algorithms/4]_Strings/Palindrome_Number.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023

#189 Create Longest_Palindromic_Substring.py
  2]_Algorithms/9]_Dynamic Programming/Longest_Palindromic_Substring.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#190 Create jump-game-ii.py
  2]_Algorithms/9]_Dynamic Programming/jump-game-ii.py
Labels: hacktoberfest-accepted, hacktoberfest2023
